/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    documents: Document;
    portraits: Portrait;
    delegates: Delegate;
    invoices: Invoice;
    'invoice-items': InvoiceItem;
    receipts: Receipt;
    payments: Payment;
    events: Event;
    registrations: Registration;
    'delegate-assignments': DelegateAssignment;
    sponsors: Sponsor;
    trainers: Trainer;
    'registration-batches': RegistrationBatch;
    committees: Committee;
    'event-committees': EventCommittee;
    organs: Organ;
    institutions: Institution;
    'institution-memberships': InstitutionMembership;
    secretariat: Secretariat;
    countries: Country;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    portraits: PortraitsSelect<false> | PortraitsSelect<true>;
    delegates: DelegatesSelect<false> | DelegatesSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    'invoice-items': InvoiceItemsSelect<false> | InvoiceItemsSelect<true>;
    receipts: ReceiptsSelect<false> | ReceiptsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    registrations: RegistrationsSelect<false> | RegistrationsSelect<true>;
    'delegate-assignments': DelegateAssignmentsSelect<false> | DelegateAssignmentsSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    trainers: TrainersSelect<false> | TrainersSelect<true>;
    'registration-batches': RegistrationBatchesSelect<false> | RegistrationBatchesSelect<true>;
    committees: CommitteesSelect<false> | CommitteesSelect<true>;
    'event-committees': EventCommitteesSelect<false> | EventCommitteesSelect<true>;
    organs: OrgansSelect<false> | OrgansSelect<true>;
    institutions: InstitutionsSelect<false> | InstitutionsSelect<true>;
    'institution-memberships': InstitutionMembershipsSelect<false> | InstitutionMembershipsSelect<true>;
    secretariat: SecretariatSelect<false> | SecretariatSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('teacher' | 'delegate' | 'secretariat' | 'admin')[];
  fullName: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Media
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout?:
    | {
        team_profiles?: (number | Secretariat)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'ourTeam';
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Add Secretariat Member
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "secretariat".
 */
export interface Secretariat {
  id: number;
  full_name: string;
  role: string;
  photo?: (number | null) | Portrait;
  email: string;
  bio: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Media
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portraits".
 */
export interface Portrait {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Media
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title?: string | null;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delegates".
 */
export interface Delegate {
  id: number;
  fullName: string;
  firstName: string;
  lastName: string;
  email?: string | null;
  phone?: string | null;
  gender?: ('male' | 'female' | 'other' | 'prefer_not_to_say') | null;
  registration: number | Registration;
  batch: number | RegistrationBatch;
  institution?: (number | null) | Institution;
  delegateState: 'pending' | 'confirmed' | 'cancelled';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations".
 */
export interface Registration {
  id: number;
  registrationNumber: string;
  event: number | Event;
  registrationType: 'individual' | 'institution';
  registeredBy: number | User;
  institution?: (number | null) | Institution;
  registrationState: 'draft' | 'active' | 'completed' | 'cancelled';
  currency: string;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Add Event
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  subtitle?: string | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  venue: string;
  cost?: number | null;
  currency?: string | null;
  eventType: 'local' | 'international';
  registrationState: 'draft' | 'open' | 'closed';
  startDate: string;
  endDate: string;
  registrationOpen: string;
  registrationClose: string;
  allowIndividualRegistration?: boolean | null;
  allowInstitutionRegistration?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutions".
 */
export interface Institution {
  id: number;
  name: string;
  institutionType: 'school' | 'university' | 'organization';
  country: string;
  city: string;
  address: string;
  email: string;
  phoneNumber: number;
  website?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registration-batches".
 */
export interface RegistrationBatch {
  id: number;
  batchNumber: string;
  registration: number | Registration;
  batchState: 'draft' | 'pending_payment' | 'partially_paid' | 'paid' | 'cancelled';
  sequence: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  invoiceNumber: string;
  registration: number | Registration;
  batch?: (number | null) | RegistrationBatch;
  invoiceState: 'draft' | 'issued' | 'partially_paid' | 'paid' | 'overdue' | 'cancelled' | 'void';
  issueDate: string;
  dueDate?: string | null;
  currency: string;
  subtotal: number;
  discount?: number | null;
  tax?: number | null;
  total: number;
  amountPaid?: number | null;
  balanceDue: number;
  pdf?: (number | null) | Media;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-items".
 */
export interface InvoiceItem {
  id: number;
  invoice: number | Invoice;
  description: string;
  quantity: number;
  unitPrice: number;
  amount: number;
  delegate?: (number | null) | Delegate;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "receipts".
 */
export interface Receipt {
  id: number;
  receiptNumber: string;
  payment: number | Payment;
  invoice: number | Invoice;
  registration: number | Registration;
  amount: number;
  currency: string;
  paymentMethod: string;
  transactionReference?: string | null;
  recipientName: string;
  recipientEmail?: string | null;
  issuedAt: string;
  receiptState: 'issued' | 'void';
  pdf?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  paymentNumber: string;
  registration: number | Registration;
  invoice: number | Invoice;
  amount: number;
  currency: string;
  provider: 'mpesa' | 'stripe' | 'flutterwave' | 'bank_transfer' | 'cash' | 'other';
  transactionReference?: string | null;
  paymentState: 'pending' | 'successful' | 'failed' | 'cancelled' | 'refunded';
  initiatedAt?: string | null;
  paidAt?: string | null;
  /**
   * Raw provider response for audit/debugging.
   */
  providerResponse?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delegate-assignments".
 */
export interface DelegateAssignment {
  id: number;
  delegate: number | Delegate;
  country: number | Country;
  eventCommittee: number | EventCommittee;
  assignmentState: 'pending' | 'assigned' | 'confirmed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  /**
   * ISO 3166-1 alpha-2 country code (e.g., US, GB, FR)
   */
  code: string;
  /**
   * Indicates whether the country is active or not
   */
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-committees".
 */
export interface EventCommittee {
  id: number;
  /**
   * Optional event-specific committee name.
   */
  name?: string | null;
  event: number | Event;
  committee: number | Committee;
  available?: boolean | null;
  capacity?: number | null;
  fee?: number | null;
  currency?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committees".
 */
export interface Committee {
  id: number;
  name: string;
  description: string;
  committee_photo?: (number | null) | Media;
  /**
   * This field is auto-generated from the Title field. Please do not edit manually.
   */
  slug?: string | null;
  committee_code: string;
  organ: number | Organ;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organs".
 */
export interface Organ {
  id: number;
  name: string;
  code: string;
  organType: 'committee_based' | 'court' | 'commission' | 'other';
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Add Sponsor
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  name: string;
  logo: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Add trainer records for QR badge verification
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainers".
 */
export interface Trainer {
  id: number;
  full_name: string;
  verification_code?: string | null;
  organ: string;
  photo?: (number | null) | Portrait;
  gender: 'male' | 'female';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institution-memberships".
 */
export interface InstitutionMembership {
  id: number;
  user: number | User;
  institution: number | Institution;
  role: 'student' | 'teacher' | 'administrator';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'portraits';
        value: number | Portrait;
      } | null)
    | ({
        relationTo: 'delegates';
        value: number | Delegate;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'invoice-items';
        value: number | InvoiceItem;
      } | null)
    | ({
        relationTo: 'receipts';
        value: number | Receipt;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'registrations';
        value: number | Registration;
      } | null)
    | ({
        relationTo: 'delegate-assignments';
        value: number | DelegateAssignment;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'trainers';
        value: number | Trainer;
      } | null)
    | ({
        relationTo: 'registration-batches';
        value: number | RegistrationBatch;
      } | null)
    | ({
        relationTo: 'committees';
        value: number | Committee;
      } | null)
    | ({
        relationTo: 'event-committees';
        value: number | EventCommittee;
      } | null)
    | ({
        relationTo: 'organs';
        value: number | Organ;
      } | null)
    | ({
        relationTo: 'institutions';
        value: number | Institution;
      } | null)
    | ({
        relationTo: 'institution-memberships';
        value: number | InstitutionMembership;
      } | null)
    | ({
        relationTo: 'secretariat';
        value: number | Secretariat;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  fullName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        ourTeam?:
          | T
          | {
              team_profiles?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portraits_select".
 */
export interface PortraitsSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delegates_select".
 */
export interface DelegatesSelect<T extends boolean = true> {
  fullName?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  gender?: T;
  registration?: T;
  batch?: T;
  institution?: T;
  delegateState?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  invoiceNumber?: T;
  registration?: T;
  batch?: T;
  invoiceState?: T;
  issueDate?: T;
  dueDate?: T;
  currency?: T;
  subtotal?: T;
  discount?: T;
  tax?: T;
  total?: T;
  amountPaid?: T;
  balanceDue?: T;
  pdf?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-items_select".
 */
export interface InvoiceItemsSelect<T extends boolean = true> {
  invoice?: T;
  description?: T;
  quantity?: T;
  unitPrice?: T;
  amount?: T;
  delegate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "receipts_select".
 */
export interface ReceiptsSelect<T extends boolean = true> {
  receiptNumber?: T;
  payment?: T;
  invoice?: T;
  registration?: T;
  amount?: T;
  currency?: T;
  paymentMethod?: T;
  transactionReference?: T;
  recipientName?: T;
  recipientEmail?: T;
  issuedAt?: T;
  receiptState?: T;
  pdf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  paymentNumber?: T;
  registration?: T;
  invoice?: T;
  amount?: T;
  currency?: T;
  provider?: T;
  transactionReference?: T;
  paymentState?: T;
  initiatedAt?: T;
  paidAt?: T;
  providerResponse?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  description?: T;
  venue?: T;
  cost?: T;
  currency?: T;
  eventType?: T;
  registrationState?: T;
  startDate?: T;
  endDate?: T;
  registrationOpen?: T;
  registrationClose?: T;
  allowIndividualRegistration?: T;
  allowInstitutionRegistration?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations_select".
 */
export interface RegistrationsSelect<T extends boolean = true> {
  registrationNumber?: T;
  event?: T;
  registrationType?: T;
  registeredBy?: T;
  institution?: T;
  registrationState?: T;
  currency?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delegate-assignments_select".
 */
export interface DelegateAssignmentsSelect<T extends boolean = true> {
  delegate?: T;
  country?: T;
  eventCommittee?: T;
  assignmentState?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainers_select".
 */
export interface TrainersSelect<T extends boolean = true> {
  full_name?: T;
  verification_code?: T;
  organ?: T;
  photo?: T;
  gender?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registration-batches_select".
 */
export interface RegistrationBatchesSelect<T extends boolean = true> {
  batchNumber?: T;
  registration?: T;
  batchState?: T;
  sequence?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committees_select".
 */
export interface CommitteesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  committee_photo?: T;
  slug?: T;
  committee_code?: T;
  organ?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-committees_select".
 */
export interface EventCommitteesSelect<T extends boolean = true> {
  name?: T;
  event?: T;
  committee?: T;
  available?: T;
  capacity?: T;
  fee?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organs_select".
 */
export interface OrgansSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  organType?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutions_select".
 */
export interface InstitutionsSelect<T extends boolean = true> {
  name?: T;
  institutionType?: T;
  country?: T;
  city?: T;
  address?: T;
  email?: T;
  phoneNumber?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institution-memberships_select".
 */
export interface InstitutionMembershipsSelect<T extends boolean = true> {
  user?: T;
  institution?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "secretariat_select".
 */
export interface SecretariatSelect<T extends boolean = true> {
  full_name?: T;
  role?: T;
  photo?: T;
  email?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}