import type { CollectionConfig } from 'payload'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const autogeneratedRegistrationNumber = async (payload: any) => {
  const lastRegistration = await payload.find({
    collection: 'registrations',
    sort: '-createdAt',
    limit: 1,
  })

  const lastNumber = lastRegistration?.docs?.[0]?.registrationNumber || 'GLUNSREG-0000'
  const lastNumericPart = parseInt(lastNumber.split('-')[1], 10)
  const newNumericPart = (lastNumericPart + 1).toString().padStart(4, '0')
  return `GLUNSREG-${newNumericPart}`
}

export const Registrations: CollectionConfig = {
  slug: 'registrations',

  admin: {
    useAsTitle: 'registrationNumber',
    defaultColumns: [
      'registrationNumber',
      'event',
      'registrationType',
      'registrationState',
      'createdAt',
    ],
  },

  fields: [
    // autogenerated registration number
    {
      name: 'registrationNumber',
      type: 'text',
      required: true,
      unique: true,
      admin: {
        readOnly: true,
      },
      hooks: {
        beforeChange: [autogeneratedRegistrationNumber],
      },
    },

    {
      name: 'event',
      type: 'relationship',
      relationTo: 'events',
      required: true,
    },

    {
      name: 'registrationType',
      type: 'select',
      required: true,
      options: [
        {
          label: 'Individual',
          value: 'individual',
        },
        {
          label: 'Institution',
          value: 'institution',
        },
      ],
    },

    {
      name: 'registeredBy',
      type: 'relationship',
      relationTo: 'users',
      required: true,
    },

    {
      name: 'institution',
      type: 'relationship',
      relationTo: 'institutions',
    },

    {
      name: 'registrationState',
      type: 'select',
      required: true,
      defaultValue: 'draft',
      options: [
        { label: 'Draft', value: 'draft' },
        { label: 'Active', value: 'active' },
        { label: 'Completed', value: 'completed' },
        { label: 'Cancelled', value: 'cancelled' },
      ],
    },

    {
      name: 'notes',
      type: 'textarea',
    },
  ],

  indexes: [
    {
      fields: ['registrationNumber'],
      unique: true,
    },
    {
      fields: ['event', 'registeredBy'],
    },
    {
      fields: ['event', 'institution'],
    },
  ],
}
